name: matrices-2b
on:
  workflow_call:
    inputs:
      client:
        description: "client"
        required: true
        type: string
      servers:
        description: "servers"
        required: true
        type: string

jobs:
  operation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false # Don't fail fast to avoid locking TF State
      matrix:
        server: ${{ fromJson(inputs.servers) }}
    name: Do (${{ inputs.client }} -> ${{ matrix.server }})
    steps:
      - shell: bash
        run: |
          echo "Do real work - ${{ inputs.client }} -> ${{ matrix.server }}"
