name: matrices-2a
on:
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: current
        with:
          sort-by: '[.version, .os, .arch] | join("-")'
          group-by: '.arch'
          nested-matrices-count: '2'
          matrix: |
            [
              {"version": "10", "os": "ubuntu-latest", "arch": "amd64"},
              {"version": "12", "os": "ubuntu-latest", "arch": "amd64"},
              {"version": "14", "os": "ubuntu-latest", "arch": "amd64"},
              {"version": "10", "os": "ubuntu-latest", "arch": "arm64"},
              {"version": "12", "os": "ubuntu-latest", "arch": "arm64"},
              {"version": "14", "os": "ubuntu-latest", "arch": "arm64"},
              {"version": "10", "os": "windows-latest", "arch": "amd64"},
              {"version": "12", "os": "windows-latest", "arch": "amd64"},
              {"version": "14", "os": "windows-latest", "arch": "amd64"},
              {"version": "10", "os": "windows-latest", "arch": "arm64"},
              {"version": "12", "os": "windows-latest", "arch": "arm64"},
              {"version": "14", "os": "windows-latest", "arch": "arm64"}
            ]

    outputs:
      matrix: "${{ steps.current.outputs.matrix }}"

  operation:
    if: ${{ needs.test.outputs.matrix != '{"include":[]}' }}
    uses: ./.github/workflows/matrices-2b.yml
    needs: [test]
    strategy:
      max-parallel: 1 # This is important to avoid ddos GHA API
      fail-fast: false # Don't fail fast to avoid locking TF State
      matrix: ${{ fromJson(needs.test.outputs.matrix) }}
    name: Group (${{ matrix.name }})
    with:
      items: ${{ matrix.items }}
