name: matrices-2a
on:
  workflow_dispatch: {}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      servers: ${{ steps.set-servers.outputs.servers }}
      clients: ${{ steps.set-clients.outputs.clients }}
    steps:
      - uses: actions/checkout@v4
      - name: Determine servers
        id: set-servers
        run: |
          SERVERS=$(jq -c 'with_entries(select(.value.role == "server" or .value.role == "both")) | keys_unsorted' implementations.json)
          echo $SERVERS
          echo "servers=$SERVERS" >> $GITHUB_OUTPUT
      - name: Determine clients
        id: set-clients
        run: |
          CLIENTS=$(jq -c 'with_entries(select(.value.role == "client" or .value.role == "both")) | keys_unsorted' implementations.json)
          echo $CLIENTS
          echo "clients=$CLIENTS" >> $GITHUB_OUTPUT

  operation:
    uses: ./.github/workflows/matrices-2b.yml
    needs: [config]
    strategy:
      fail-fast: false
      matrix:
        client: ${{ fromJson(needs.config.outputs.clients) }}
    name: Group (${{ matrix.client }})
    with:
      client: ${{ matrix.client }}
      servers: ${{ needs.config.outputs.servers }}
